'use client';
import './globals.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
import '../assets/styles/bootstrap.custom.css';
import '../assets/styles/index.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Container } from 'react-bootstrap';
import { Providers } from '@/redux/provider';

export const metadata = {
  title: 'Pro Shop',
  description: 'Generated by Pro Shop',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main className='py-3 '>
          <Providers>
            <Container>{children}</Container>
          </Providers>
        </main>
        <Footer />
      </body>
    </html>
  );
}
